apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-core-helm
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:hauke-d/homelab.git
      revision: main
      files:
      - path: "kubernetes/cluster-core/helm/**/config.json"
  template:
    metadata:
      name: '{{path[3]}}'
      namespace: argocd
    spec:
      project: cluster-core
      sources:
      - repoURL: '{{repoURL}}'
        targetRevision: '{{version}}'
        chart: '{{chart}}'
        helm:
          valueFiles:
            - '$values/kubernetes/cluster-core/helm/{{path[3]}}/values.yaml'
    - ref: values
      repoURL: 'git@github.com:hauke-d/homelab.git'
      targetRevision: main
      destination:
        namespace: '{{namespace}}'
        server: 'https://kubernetes.default.svc'
