apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-core-helm
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:hauke-d/homelab.git
      revision: main
      files:
      - path: "kubernetes/cluster-core/helm/**/config.json"
  template:
    metadata:
      name: '{{path[3]}}'
      namespace: argocd
    spec:
      project: cluster-core
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{version}}'
        chart: '{{chart}}'
      destination:
        server: '{{namespace}}'
        namespace: guestbook
