---
- name: Set up DHCP server
  vyos_config:
    lines:
    - set service dhcp-server shared-network-name LAN subnet {{home.subnet}}{{home.cidr}} range 0 start {{home.dhcp.start}}
    - set service dhcp-server shared-network-name LAN subnet {{home.subnet}}{{home.cidr}} range 0 stop {{home.dhcp.end}}
    - set service dhcp-server shared-network-name LAN subnet {{lab.subnet}}{{lab.cidr}} range 0 start {{lab.dhcp.start}}
    - set service dhcp-server shared-network-name LAN subnet {{lab.subnet}}{{lab.cidr}} range 0 stop {{lab.dhcp.end}}