---
- name: Set up DNS
  vyos_config:
    lines:
    - set service dns forwarding allow-from {{ local_range }}
    - set service dns forwarding allow-from {{ wan.subnet }}{{ wan.cidr }}
    - set service dns forwarding cache-size 10000
    - set service dns forwarding listen-address {{ lab.address }}
    - set service dns forwarding listen-address {{ lab.vlans.hosts.address }}
    - set service dns forwarding listen-address {{ lab.vlans.shared.address }}
    - set service dns forwarding listen-address {{ lab.vlans.kubernetes.address }}
    - set service dns forwarding listen-address {{ wan.address }}
    - set service dns forwarding name-server 1.0.0.1
    - set service dns forwarding name-server 1.1.1.1
    - set system name-server {{ lab.address }}
