---
- name: Allow traffic from router to everywhere
  vyos_config:
    lines:
    - set firewall name LOCAL-HOME default-action accept
    - set firewall name LOCAL-LAB default-action accept
    - set firewall name LOCAL-MGMT default-action accept
    - set firewall name LOCAL-WAN default-action accept

- name: Allow traffic from LAN to the internet
  vyos_config:
    lines:
    - set firewall name HOME-WAN default-action accept
    - set firewall name LAB-WAN default-action accept
    - set firewall name MGMT-WAN default-action accept

- name: Allow traffic from LAN to the router
  vyos_config:
    lines:
    - set firewall name HOME-LOCAL default-action accept
    - set firewall name LAB-LOCAL default-action accept
    - set firewall name MGMT-LOCAL default-action accept

- name: Block inbound traffic to router
  vyos_config:
    lines:
    - set firewall name WAN-LOCAL default-action drop
    - set firewall name WAN-LOCAL rule 10 action accept
    - set firewall name WAN-LOCAL rule 10 description 'Allow traffic on established outbound connections'
    - set firewall name WAN-LOCAL rule 10 state established enable
    - set firewall name WAN-LOCAL rule 10 state related enable

- name: Block inbound traffic to local network
  vyos_config:
    lines:
    - set firewall name WAN-LAN default-action drop
    - set firewall name WAN-LAN rule 10 action accept
    - set firewall name WAN-LAN rule 10 description 'Allow traffic on established outbound connections'
    - set firewall name WAN-LAN rule 10 state established enable
    - set firewall name WAN-LAN rule 10 state related enable

# Needs to run as one task as committing might shut us out otherwise
- name: Set up zones 
  vyos_config:
    lines:
    - set firewall zone LOCAL local-zone
    - set firewall zone LOCAL from WAN firewall name WAN-LOCAL
    - set firewall zone LOCAL from LAB firewall name LAB-LOCAL
    - set firewall zone LOCAL from HOME firewall name HOME-LOCAL
    - set firewall zone LOCAL from MGMT firewall name MGMT-LOCAL

    - set firewall zone WAN default-action drop
    - set firewall zone WAN from LOCAL firewall name LOCAL-WAN
    - set firewall zone WAN from HOME firewall name HOME-WAN
    - set firewall zone WAN from LAB firewall name LAB-WAN
    - set firewall zone WAN from MGMT firewall name MGMT-WAN
    - set firewall zone WAN interface {{wan.interface}}

    - set firewall zone HOME default-action drop
    - set firewall zone HOME from LOCAL firewall name LOCAL-HOME
    - set firewall zone HOME from WAN firewall name WAN-LAN
    - set firewall zone HOME interface {{home.interface}}

    - set firewall zone LAB default-action drop
    - set firewall zone LAB from LOCAL firewall name LOCAL-LAB
    - set firewall zone LAB from WAN firewall name WAN-LAN
    - set firewall zone LAB interface {{lab.interface}}

    - set firewall zone MGMT default-action drop
    - set firewall zone MGMT from LOCAL firewall name LOCAL-MGMT
    - set firewall zone MGMT from WAN firewall name WAN-LAN
    - set firewall zone MGMT interface {{mgmt.interface}}
