---
- name: Interfaces - State & description
  vyos_interfaces:
    config:
      - name: "{{ wan.interface }}"
        description: "WAN"
      - name: "{{ home.interface }}"
        description: "HOME"
      - name: "{{ lab.interface }}"
        description: "LAB"
      - name: "{{ mgmt.interface }}"
        description: "MGMT"
      - name: lo
    state: replaced

- name: Interfaces - L3 config
  vyos_l3_interfaces:
    config:
      - name: "{{ wan.interface }}"
        ipv4:
          - address: dhcp
      - name: "{{ home.interface }}"
        ipv4:
          - address: "{{ home.address }}{{ home.cidr }}"
      - name: "{{ lab.interface }}"
        ipv4:
          - address: "{{ lab.address }}{{ lab.cidr }}"
      - name: "{{ mgmt.interface }}"
        ipv4:
          - address: "{{ mgmt.address }}{{ mgmt.cidr }}"
    state: replaced

