---
- name: Interfaces - State & description
  vyos_interfaces:
    config:
      - name: "{{ wan.interface }}"
        description: "WAN"
      - name: "{{ lab.interface }}"
        description: "LAB"
        vifs:
        - vlan_id: "{{ lab.vlans.hosts.id }}"
          description: "HOSTS"
        - vlan_id: "{{ lab.vlans.shared.id }}"
          description: "SHARED"
        - vlan_id: "{{ lab.vlans.kubernetes.id }}"
          description: "KUBERNETES"
      - name: lo
    state: overridden

- name: Interfaces - L3 config
  vyos_l3_interfaces:
    config:
      - name: "{{ wan.interface }}"
        ipv4:
          - address: "{{ wan.address }}{{ wan.cidr }}"
      - name: "{{ lab.interface }}"
        ipv4:
          - address: "{{ lab.address }}{{ lab.cidr }}"
        vifs:
        - vlan_id: "{{ lab.vlans.hosts.id }}"
          ipv4:
            - address: "{{ lab.vlans.hosts.address }}{{ lab.vlans.hosts.cidr }}"
        - vlan_id: "{{ lab.vlans.shared.id }}"
          ipv4:
            - address: "{{ lab.vlans.shared.address }}{{ lab.vlans.shared.cidr }}"
        - vlan_id: "{{ lab.vlans.kubernetes.id }}"
          ipv4:
            - address: "{{ lab.vlans.kubernetes.address }}{{ lab.vlans.kubernetes.cidr }}"
    state: overridden

- name: WAN Default gateway
  vyos_config:
    lines:
    - set protocols static route 0.0.0.0/0 next-hop {{wan.gateway}}
