cluster:
  allowSchedulingOnControlPlanes: true
  network:
    podSubnets: 
    - 10.244.0.0/16
    serviceSubnets: 
    - 10.96.0.0/16
    cni:
      name: none
  proxy:
    disabled: true
machine:
  install:
    disk: /dev/sda
  network:
    hostname: ${hostname}
