cluster:
  allowSchedulingOnControlPlanes: true
  network:
    dnsDomain: cluster.local
    podSubnets: 
    - 10.244.0.0/12
    serviceSubnets: 
    - 10.96.0.0/12
    cni:
      name: none
  proxy:
    disabled: true
  controlPlane:
    endpoint: https://${controlplane_virtual_ip}:6443
  # Automatically approve kubelet CSRs
  extraManifests:
    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
machine:
  install:
    disk: /dev/sda
  network:
    hostname: ${hostname}
    interfaces:
    - interface: eth0
      vip:
        ip: ${controlplane_virtual_ip}
  kubelet:
    extraArgs:
      rotate-server-certificates: true
