local_range: "10.8.0.0/16"

wan:
  subnet: "192.168.0.0"
  address: "192.168.0.254"
  cidr: "/24"
  gateway: "192.168.0.1"
  interface: eth0

lab:
  interface: eth1
  subnet: "10.8.0.0"
  cidr: "/21"
  address: "10.8.0.1"
  dhcp:
    start: "10.8.0.20"
    end: "10.8.0.200"
  vlans:
    hosts:
      id: 8
      subnet: "10.8.8.0"
      cidr: "/21"
      address: "10.8.8.1"
    shared:
      id: 16
      subnet: "10.8.16.0"
      cidr: "/21"
      address: "10.8.16.1"
    kubernetes:
      id: 24
      subnet: "10.8.24.0"
      cidr: "/21"
      address: "10.8.24.1"
      dhcp:
        start: "10.8.24.20"
        end: "10.8.24.200"
