---
- name: Basic system setup
  hosts: proxmox_hosts
  become: true
  vars:
    ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJhhadIjv/5D2osI8P38XcEBlKQczcgffw3dB1Vbt8Vm

  tasks:
  - name: Ensure ansible user exists
    user:
      state: present
      name: ansible
      shell: /bin/bash
      comment: Ansible automation user

  - name: Add ssh key for ansible user
    authorized_key:
      state: present
      user: ansible
      key: "{{ ssh_public_key }}"

  - name: Use proxmox no-subscription repo
    copy:
      content: 'deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription'
      dest: /etc/apt/sources.list.d/pve-no-subscription.list
      mode: 0440

  - name: Remove proxmox enterprise repo
    file:
      state: absent
      path: /etc/apt/sources.list.d/pve-enterprise.list

  - name: Install packages
    apt:
      name:
      - sudo
      - vim-nox
      update_cache: true
      state: present

  - name: Allow sudo without password for ansible user
    copy:
      content: 'ansible ALL=(ALL:ALL) NOPASSWD:ALL'
      dest: /etc/sudoers.d/ansible
      mode: 0440

  - name: Disable SSH root login
    lineinfile: 
      state: present
      dest: /etc/ssh/sshd_config
      regexp: "^PermitRootLogin" 
      line: PermitRootLogin no
    notify:
        - restart sshd


  - name: Disable SSH password login
    lineinfile: 
      state: present
      dest: /etc/ssh/sshd_config 
      regexp: "^PasswordAuthentication" 
      line: PasswordAuthentication no
    notify:
      - restart sshd
  
  - name: Ensure danish locale exists
    community.general.locale_gen:
      name: da_DK.UTF-8
      state: present

  - name: Disable speaker kernel module
    community.general.kernel_blacklist:
      name: pcspkr

  - name: Remove speaker module from kernel (to not require reboot)
    command: modprobe -r pcspkr
    changed_when: false
  
  - name: Update /etc/hosts
    template:
      src: hosts.j2
      dest: /etc/hosts
      mode: 0644

  handlers:
  - name: restart sshd
    service:
      name: ssh
      state: restarted